supervisor:
  starting_smiles: null
  working_directory: /home/giacomo/Documents/LCP_runs/sampler_test
  protein_pdb: null
  log_file: ./log.dat
  sampler:
    name: GCNActiveLearning
    kwargs:
      featurization:
        name: FingerprintFeaturization
        kwargs:
          n_bits: 1024
      net:
        name: Encoder
        kwargs:
          input_ch: 1024
          latent_ch: 1
          hidden_ch: null
          # layer_instance:
          intermediate_layer: null
          use_batch_norm: false
          num_layers: 5
          num_layers_head: 3
          # net_init: null
          use_vae: false

      best_n: 20
      epochs: 30
      lr: 0.001
      batch_size: 64
      chkpt_path: null
      save_every: 50

  score: null
  n_child: 1000
  n_threads: 1
  domain_selection: null
  n_max_parallel_process: 1
  lag_iterations: 5
  best_n_ligands: 10
  run_id: 0