supervisor:
  starting_smiles: OCCCC([O-])=O
  working_directory: /home/giacomo/Documents/LCP_runs/RUN_1/docking
  protein_pdb: 6fff
  log_file: /home/giacomo/Documents/LCP_runs/RUN_1/log.dat
  sampler:
    name: GCNActiveLearning
    kwargs:
      featurization:
        name: OneHotFeaturizer
        kwargs:
          padlength: 120
      net:
        name: Encoder
        kwargs:
          input_ch: 35
          latent_ch: 1
          hidden_ch: 128
          layer_instance: conv1d
          intermediate_layer:
            name: Pool1D
            kwargs:
              pool_shape: 1
              use_flatten: true
          use_batch_norm: false
          num_layers: 5
          num_layers_head: 3
          # net_init: null
          use_vae: false

      best_n: 10
      epochs: 30
      lr: 0.001
      batch_size: 64
      chkpt_path: null
      save_every: 50

  score:
    name: Autodock
    kwargs:
      output_file: /home/giacomo/Documents/LCP_runs/RUN_1/docking_res.txt
      folder: /home/giacomo/Documents/LCP_runs/RUN_1/docking
      keep_ions: true
      open_mode: w
      n_threads: 1

  n_child: 100
  n_threads: 1
  domain_selection: null
  n_max_parallel_process: 1
  lag_iterations: 5
  best_n_ligands: 10
  run_id: 0